fix avatar
mezonai/mezon pull request #2365
Opened 2024-08-01 08:53 UTC by codengoo

2024-08-01 10:25 UTC, phuocnguyenncc commented on apps/mobile/src/app/screens/home/homedrawer/components/AvatarMessage/index.tsx
> +	const userById = useSelector(selectMemberByUserId(id || ''));
get avatar from message

2024-08-02 07:21 UTC, sontung-nccvn commented on apps/mobile/src/app/screens/home/homedrawer/MessageItem.tsx
> +						username={isDM ? message?.display_name || message?.user?.username : message?.user?.username}
refactor

2024-08-02 07:22 UTC, sontung-nccvn commented on apps/mobile/src/app/screens/home/homedrawer/components/UserProfile/index.tsx
> +				{ backgroundColor: user?.avatar_url || user?.avatarSm || userById?.user?.avatar_url ? color : Colors.titleReset }
duplicate

2024-08-02 07:24 UTC, sontung-nccvn commented on apps/mobile/src/app/temp-ui/MezonAvatar/index.tsx
> +			{userStatus && <View style={[styles.statusCircle, userStatus ? styles.online : styles.offline]} />}
!!userStatus

2024-08-05 04:55 UTC, phuocnguyenncc commented on apps/mobile/src/app/screens/home/homedrawer/components/UserProfile/index.tsx
> +						avatarUrl={userById?.user?.avatar_url || user?.avatar_url || user?.avatarSm}
not use userById

2024-08-05 08:17 UTC, phuocnguyenncc approved these changes

2024-08-05 08:22 UTC, phuocnguyenncc requested changes
revert keep using userById in UserProfile

2024-08-05 09:00 UTC, phuocnguyenncc commented on apps/mobile/src/app/screens/home/homedrawer/MessageItem.tsx
> +	}, [isDM, message]);
dependency should [isDM, message?.display_name, message?.user?.username]);

2024-08-05 09:18 UTC, phuocnguyenncc approved these changes

2024-08-05 10:43 UTC, merged