add component message system when pin
mezonai/mezon pull request #4578
Opened 2024-10-31 06:40 UTC by thanhlong1203

2024-10-31 09:53 UTC, thanhlong1203 commented
em đang cập nhật lại thêm ạ

2024-11-01 10:32 UTC, nqdd commented on libs/components/src/lib/components/MessageWithUser/MessageLineSystem.tsx
> +// eslint-disable-next-line @nx/enforce-module-boundaries
check lại lint nhé, ko disable lỗi này

2024-11-01 10:33 UTC, nqdd commented on libs/store/src/lib/messages/messages.slice.ts
>  				case 0: {
thay luôn enum vào đây nha

2024-11-01 10:33 UTC, nqdd requested changes
Check comment giúp a nhé

2024-11-04 03:35 UTC, nqdd approved these changes

2024-11-04 03:56 UTC, merged