add recent emojis to message options
mezonai/mezon pull request #4598
Opened 2024-10-31 15:45 UTC by thanhlong1203

2024-11-01 10:27 UTC, nqdd approved these changes

2024-11-01 10:29 UTC, nqdd commented on libs/components/src/lib/components/Message/ChannelMessageOpt.tsx
> +function useRecentEmojiBuilder(message: IMessageWithUser) {
cái này là component mà. Có phải hook đâu

2024-11-01 10:29 UTC, nqdd requested changes
Check comemnt giúp a nhé

2024-11-01 10:34 UTC, thanhlong1203 commented on libs/components/src/lib/components/Message/ChannelMessageOpt.tsx
> +function useRecentEmojiBuilder(message: IMessageWithUser) {
để em xem lại ạ

2024-11-04 03:34 UTC, nqdd approved these changes

2024-11-04 03:56 UTC, merged